### ISSUE TITLE
[Forge] Cannot join world due to "invalid player data"

### ISSUE THREAD

**Issue by FlynnLies** [QuantumXenon/origins-plus-plus#155]
*Please check the pinned issues "Solutions to Frequent Issues" and "Known Forge Issues" before posting a new report*

**Loader**
Forge

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.2.6
- Origins Version: 1.5.0.6
- Origins++ Version: 2.0
- Pehkui Version: 3.7.0

**Problem**
Either cannot join world after generation or can't join after loading in a second time due to `invalid player data`.
The log says 
```
[Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
	at net.minecraft.network.protocol.game.ClientboundCustomPayloadPacket.<init>(ClientboundCustomPayloadPacket.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraftforge.network.NetworkDirection.lambda$static$1(NetworkDirection.java:28) ~[forge-1.19.2-43.2.6-universal.jar%23160!/:?]
	at net.minecraftforge.network.NetworkDirection.buildPacket(NetworkDirection.java:79) ~[forge-1.19.2-43.2.6-universal.jar%23160!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112) ~[forge-1.19.2-43.2.6-universal.jar%23160!/:?]
	at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.19.2-43.2.6-universal.jar%23160!/:?]
	at io.github.edwinmindcraft.calio.common.registry.CalioDynamicRegistryManager.synchronize(CalioDynamicRegistryManager.java:138) ~[calio-forge-1.19.2-1.6.0.3.jar%23164!/:1.19.2-1.6.0.3]
	at io.github.edwinmindcraft.calio.common.CalioEventHandler.onDatapack(CalioEventHandler.java:35) ~[calio-forge-1.19.2-1.6.0.3.jar%23164!/:1.19.2-1.6.0.3]
	at io.github.edwinmindcraft.calio.common.__CalioEventHandler_onDatapack_OnDatapackSyncEvent.invoke(.dynamic) ~[calio-forge-1.19.2-1.6.0.3.jar%23164!/:1.19.2-1.6.0.3]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:173) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23155!/:?]
```

**Notes**
Tested on fresh install with only origins++ and requirements.

**Comment by QuantumXenon** [comment]
Do you have Connectivity installed?

**Comment by FlynnLies** [comment]
The only mods i had were
- Caelus 3.0.0.6
- Origins: 1.5.0.5
- Origins++: 2.0
- Pehkui: 3.7.0
- XLPackets: 1.18.2+

With `XLPackets` it doesn't even let me join into the world. Stops after 100%.

Changing `XLPackets ` to `Connectivity` did let me load into the world, saving an loading again results in `invalid player data` again though. I need to restart minecraft to be able to get back in, but at least it works now. Consider changing/adding that as a dependecy on Curseforge.

Putting it in a server works semi-better, when joining I also got some odd errors for a few times, it did let me join eventually though i guess.

**Comment by QuantumXenon** [comment]
Ok great. I have Connectivity as an Optional Dependency on CurseForge at the moment, so I could bump that up to a mandatory one.

As for the saving and reloading, I believe that is a bug with Origins (Forge), but at least you are able to get around it (albeit in an inconvenient way)

**Comment by QuantumXenon** [comment]
@FlynnLies see 6905b1f
