### ISSUE TITLE
Bugs and issues

### ISSUE THREAD

**Issue by andyrdz228** [QuantumXenon/origins-plus-plus#287]
*Please check the pinned issues "Known Forge Issues" and "Known Fabric/Quilt Issues" before posting a new report*

**Loader**
Forge 

**Versions**
- Minecraft Version: 1.19.2
- Mod Loader Version: 43.3.0
- Origins Version: 1.19.2-1.7.1.3
- Origins++ Version: 2.2
- Pehkui Version: 3.7.8+1.19.2

**Origin**
Blazian
**Power**
No powers or abilities work

**Notes**
Trying to create a new world, it either crashes trying to create it and gives the broken registry apoli issue given or the world finishes loading with no popup to pick an origin and no origins from origin++ can be used even with commands, or it does load and the blazian origin is broken; nether mobs are hostile, no fire resistance, no abilities, but still spawn in the nether

**Comment by nightlocust** [comment]
Sure thing. Here you go!
[spoiler][14:39:23] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.15.1
[14:39:23] [main/INFO]: Loading 69 mods:
	- fabric-api 0.91.2+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.78+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.8+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.42+a44e16a6a0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.1.2+95a8ac51a0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.11+52b3ebe5a0
	   |-- fabric-registry-sync-v0 4.0.9+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.11+239dafd8a0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.44+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.12+4944b5a5a0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.15.1
	   \-- mixinextras 0.3.1
	- java 17
	- minecraft 1.20.2
	- origins 1.11.3
	   |-- apoli 2.10.3
	   |    |-- additionalentityattributes 1.5.0+1.20.2
	   |    |-- calio 1.12.2
	   |    |    |-- org_quiltmc_parsers_gson 0.2.1
	   |    |    \-- org_quiltmc_parsers_json 0.2.1
	   |    |-- cardinal-components-base 5.3.0
	   |    |-- cardinal-components-entity 5.3.0
	   |    |-- cloth-config 12.0.109
	   |    |    \-- cloth-basic-math 0.6.1
	   |    \-- playerabilitylib 1.9.0
	   \-- reach-entity-attributes 2.4.0
	- origins-plus-plus 2.2
	- pehkui 3.7.11+1.14.4-1.20.2
	   \-- kanos_config 0.4.1+1.14.4-1.19.4
[14:39:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/nicka/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[14:39:23] [main/INFO]: Compatibility level set to JAVA_17
[14:39:24] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.1).
[14:39:28] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 134 milliseconds
[14:39:30] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[14:39:31] [Render thread/INFO]: Setting user: nightlocust
[14:39:31] [Render thread/INFO]: Apoli 2.10.3 has initialized. Ready to power up your game!
[14:39:31] [Render thread/INFO]: Origins 1.11.3 is initializing. Have fun!
[14:39:31] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[14:39:32] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[14:39:33] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (additionalentityattributes, apoli, calio, cardinal-components-base, cardinal-components-entity, cloth-config, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, kanos_config, origins, origins-plus-plus, pehkui, playerabilitylib, reach-entity-attributes)
[14:39:33] [Worker-Main-14/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[14:39:34] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[14:39:34] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[14:39:36] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speaker (Realtek(R) Audio)
[14:39:36] [Render thread/INFO]: Sound engine started
[14:39:36] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[14:39:36] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[14:39:36] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[14:39:36] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[14:39:36] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[14:39:36] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[14:39:36] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[14:39:36] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[14:39:36] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[14:39:36] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[14:39:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[14:39:36] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[14:39:36] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[14:39:36] [Render thread/INFO]: Created: 1024x1024x0 minecraft:textures/atlas/gui.png-atlas
[14:39:44] [Render thread/INFO]: Loaded 7 recipes
[14:39:44] [Render thread/INFO]: Loaded 1282 advancements
[14:39:44] [Render thread/INFO]: Finished loading powers from data files. Registry contains 2544 powers.
[14:39:44] [Render thread/INFO]: Finished loading origins from data files. Registry contains 129 origins.
[14:39:44] [Render thread/INFO]: Loading origin layer from data files...
[14:39:44] [Render thread/INFO]: Trying to read origin layer file "origins:origin" from data pack [origins]
[14:39:44] [Render thread/INFO]: Trying to read origin layer file "origins:origin" from data pack [origins-plus-plus]
[14:39:44] [Render thread/INFO]: Finished loading origin layers. Merging similar origin layers...
[14:39:44] [Render thread/INFO]: Finished merging similar origin layers from data files. Read 1 origin layers.
[14:39:44] [Render thread/INFO]: Finished loading global power sets. Merging similar global power sets...
[14:39:44] [Render thread/INFO]: Finished merging similar global power sets from data files. Loaded 0 global power sets.
[15:12:31] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.095 ms
[15:12:31] [Server thread/INFO]: Starting integrated minecraft server version 1.20.2
[15:12:31] [Server thread/INFO]: Generating keypair
[15:12:33] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[15:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[15:12:34] [Render thread/INFO]: Preparing spawn area: 0%
[15:12:35] [Render thread/INFO]: Preparing spawn area: 3%
[15:12:35] [Render thread/INFO]: Preparing spawn area: 6%
[15:12:36] [Render thread/INFO]: Preparing spawn area: 11%
[15:12:36] [Render thread/INFO]: Preparing spawn area: 16%
[15:12:37] [Render thread/INFO]: Preparing spawn area: 23%
[15:12:37] [Render thread/INFO]: Preparing spawn area: 29%
[15:12:38] [Render thread/INFO]: Preparing spawn area: 36%
[15:12:38] [Render thread/INFO]: Preparing spawn area: 43%
[15:12:39] [Render thread/INFO]: Preparing spawn area: 51%
[15:12:39] [Render thread/INFO]: Preparing spawn area: 58%
[15:12:40] [Render thread/INFO]: Preparing spawn area: 68%
[15:12:40] [Render thread/INFO]: Preparing spawn area: 74%
[15:12:41] [Render thread/INFO]: Preparing spawn area: 83%
[15:12:41] [Render thread/INFO]: Preparing spawn area: 88%
[15:12:42] [Render thread/INFO]: Preparing spawn area: 99%
[15:12:42] [Render thread/INFO]: Time elapsed: 8527 ms
[15:12:42] [Server thread/INFO]: Changing view distance to 12, from 10
[15:12:42] [Server thread/INFO]: Changing simulation distance to 12, from 0
[15:12:43] [Server thread/INFO]: nightlocust[local:E:18ddf4c7] logged in with entity id 100 at (914.5, 71.0, -140.5)
[15:12:43] [Server thread/INFO]: nightlocust joined the game
[15:12:43] [Render thread/ERROR]: Error executing task on Client
java.lang.IllegalArgumentException: Duplicate origin id tried to register: 'origins:empty'
	at io.github.apace100.origins.origin.OriginRegistry.register(OriginRegistry.java:20) ~[Origins-1.20.2-1.11.3.jar:?]
	at io.github.apace100.origins.networking.ModPacketsS2C.lambda$receiveOriginList$2(ModPacketsS2C.java:88) ~[Origins-1.20.2-1.11.3.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at io.github.apace100.origins.networking.ModPacketsS2C.receiveOriginList(ModPacketsS2C.java:86) ~[Origins-1.20.2-1.11.3.jar:?]
	at net.fabricmc.fabric.api.client.networking.v1.ClientPlayNetworking.lambda$wrapTyped$1(ClientPlayNetworking.java:391) ~[fabric-networking-api-v1-3.1.2+95a8ac51a0-628a6791de532f2.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1231) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.15.1-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.1.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.1.jar:?]
[15:12:44] [Render thread/INFO]: Loaded 2 advancements
[15:57:20] [Server thread/INFO]: Player nightlocust chose origin "origins-plus-plus:wizard" for layer "origins:origin"
[15:57:21] [Server thread/INFO]: Saving and pausing game...
[15:57:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:overworld
[15:57:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_nether
[15:57:21] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_end
[15:57:30] [Server thread/INFO]: [nightlocust: Set own game mode to Creative Mode]
[15:57:30] [Render thread/INFO]: [System] [CHAT] Set own game mode to Creative Mode
[15:57:45] [Server thread/INFO]: Saving and pausing game...
[15:57:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:overworld
[15:57:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_nether
[15:57:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_end
[15:57:54] [Server thread/INFO]: Player nightlocust chose origin "origins-plus-plus:wizard" for layer "origins:origin"
[15:58:04] [Server thread/INFO]: [nightlocust: Set own game mode to Survival Mode]
[15:58:04] [Render thread/INFO]: [System] [CHAT] Set own game mode to Survival Mode
[15:58:22] [Server thread/INFO]: Saving and pausing game...
[15:58:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:overworld
[15:58:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_nether
[15:58:22] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_end
[15:59:25] [Server thread/INFO]: Saving and pausing game...
[15:59:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:overworld
[15:59:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_nether
[15:59:25] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_end
[15:59:45] [Server thread/INFO]: nightlocust lost connection: Disconnected
[15:59:45] [Server thread/INFO]: nightlocust left the game
[15:59:45] [Server thread/INFO]: Stopping singleplayer server as player logged out
[15:59:45] [Server thread/INFO]: Stopping server
[15:59:45] [Server thread/INFO]: Saving players
[15:59:45] [Server thread/INFO]: Saving worlds
[15:59:45] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:overworld
[15:59:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_nether
[15:59:46] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Origins; It's Snowtime]'/minecraft:the_end
[15:59:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (Origins; It's Snowtime): All chunks are saved
[15:59:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[15:59:46] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:59:46] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[16:02:23] [Render thread/INFO]: Stopping![/spoiler]
