### ISSUE TITLE
Incompatibility with JourneyMap

### ISSUE THREAD

**Issue by 7PkmnV** [QuantumXenon/origins-plus-plus#78]
When origins++ and journeymap are installed, minecraft will successfully launch, but is incredibly unstable. When trying to load a world, it will fail due to a ConcurrentModificationException, and the world will disappear until minecraft is restarted. However loading another world will work, but upon logging off the game will crash./
[crash-2022-09-15_14.24.45-server.txt](https://github.com/QuantumXenon/origins-plus-plus/files/9578718/crash-2022-09-15_14.24.45-server.txt)

**Comment by QuantumXenon** [comment]
If you remove Origins++, does everything work as expected?

**Comment by QuantumXenon** [comment]
It looks to me like JourneyMap is causing the issue: 
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.m_129880_(net.minecraft.resources.ResourceKey)" because the return value of "journeymap.common.LoaderHooks.getServer()" is null
	at journeymap.common.events.forge.ForgeServerEvents.onServerTickEvent(ForgeServerEvents.java:74) ~[journeymap-1.18.2-5.8.5-forge.jar%23103!/:1.18.2-5.8.5] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_688_ForgeServerEvents_onServerTickEvent_ServerTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreServerTick(ForgeEventFactory.java:937) ~[forge-1.18.2-40.1.80-universal.jar%23134!/:?] {re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:840) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23129!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) ~[?:?] {}
```
